name: Quarto Publish

on:
  push:
    branches:
      - MF02-PRA02-EmmaAlonsoMcCoy
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: my-quarto-site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}